services:
  postgres:
    image: postgres:16
    container_name: api6_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api6_postgres
    ports:
      - "5432:5432"
    networks:
      - api6

  pg-key:
    image: postgres:16
    container_name: api6_keys
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api6_keys
    ports:
      - "5433:5432"
    networks:
      - api6

  mongo:
    image: mongo:latest
    container_name: api6_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: api6_mongo
    ports:
      - "27017:27017"
    networks:
      - api6

networks:
  api6:
    driver: bridge
