---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install PNPM
        run: |
          corepack enable
          corepack prepare pnpm@9.10 --activate
          pnpm --version

      - name: Install Nx and Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clear Poetry Cache
        run: poetry cache clear --all pypi

      - name: Lock dependencies and Install with Poetry
        run: |
          poetry lock
          poetry install

      - name: Set Shas for Nx Cache
        uses: nrwl/nx-set-shas@v4

      - name: Run Affected
        run: pnpm nx affected -t lint test build
